// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: rpc.proto

package hubble_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HubService_SubmitMessage_FullMethodName                      = "/HubService/SubmitMessage"
	HubService_ValidateMessage_FullMethodName                    = "/HubService/ValidateMessage"
	HubService_Subscribe_FullMethodName                          = "/HubService/Subscribe"
	HubService_GetEvent_FullMethodName                           = "/HubService/GetEvent"
	HubService_GetCast_FullMethodName                            = "/HubService/GetCast"
	HubService_GetCastsByFid_FullMethodName                      = "/HubService/GetCastsByFid"
	HubService_GetCastsByParent_FullMethodName                   = "/HubService/GetCastsByParent"
	HubService_GetCastsByMention_FullMethodName                  = "/HubService/GetCastsByMention"
	HubService_GetReaction_FullMethodName                        = "/HubService/GetReaction"
	HubService_GetReactionsByFid_FullMethodName                  = "/HubService/GetReactionsByFid"
	HubService_GetReactionsByCast_FullMethodName                 = "/HubService/GetReactionsByCast"
	HubService_GetReactionsByTarget_FullMethodName               = "/HubService/GetReactionsByTarget"
	HubService_GetUserData_FullMethodName                        = "/HubService/GetUserData"
	HubService_GetUserDataByFid_FullMethodName                   = "/HubService/GetUserDataByFid"
	HubService_GetUsernameProof_FullMethodName                   = "/HubService/GetUsernameProof"
	HubService_GetUserNameProofsByFid_FullMethodName             = "/HubService/GetUserNameProofsByFid"
	HubService_GetVerification_FullMethodName                    = "/HubService/GetVerification"
	HubService_GetVerificationsByFid_FullMethodName              = "/HubService/GetVerificationsByFid"
	HubService_GetOnChainSigner_FullMethodName                   = "/HubService/GetOnChainSigner"
	HubService_GetOnChainSignersByFid_FullMethodName             = "/HubService/GetOnChainSignersByFid"
	HubService_GetOnChainEvents_FullMethodName                   = "/HubService/GetOnChainEvents"
	HubService_GetIdRegistryOnChainEvent_FullMethodName          = "/HubService/GetIdRegistryOnChainEvent"
	HubService_GetIdRegistryOnChainEventByAddress_FullMethodName = "/HubService/GetIdRegistryOnChainEventByAddress"
	HubService_GetCurrentStorageLimitsByFid_FullMethodName       = "/HubService/GetCurrentStorageLimitsByFid"
	HubService_GetFids_FullMethodName                            = "/HubService/GetFids"
	HubService_GetLink_FullMethodName                            = "/HubService/GetLink"
	HubService_GetLinksByFid_FullMethodName                      = "/HubService/GetLinksByFid"
	HubService_GetLinksByTarget_FullMethodName                   = "/HubService/GetLinksByTarget"
	HubService_GetAllCastMessagesByFid_FullMethodName            = "/HubService/GetAllCastMessagesByFid"
	HubService_GetAllReactionMessagesByFid_FullMethodName        = "/HubService/GetAllReactionMessagesByFid"
	HubService_GetAllVerificationMessagesByFid_FullMethodName    = "/HubService/GetAllVerificationMessagesByFid"
	HubService_GetAllUserDataMessagesByFid_FullMethodName        = "/HubService/GetAllUserDataMessagesByFid"
	HubService_GetAllLinkMessagesByFid_FullMethodName            = "/HubService/GetAllLinkMessagesByFid"
	HubService_GetLinkCompactStateMessageByFid_FullMethodName    = "/HubService/GetLinkCompactStateMessageByFid"
	HubService_GetInfo_FullMethodName                            = "/HubService/GetInfo"
	HubService_GetCurrentPeers_FullMethodName                    = "/HubService/GetCurrentPeers"
	HubService_StopSync_FullMethodName                           = "/HubService/StopSync"
	HubService_ForceSync_FullMethodName                          = "/HubService/ForceSync"
	HubService_GetSyncStatus_FullMethodName                      = "/HubService/GetSyncStatus"
	HubService_GetAllSyncIdsByPrefix_FullMethodName              = "/HubService/GetAllSyncIdsByPrefix"
	HubService_GetAllMessagesBySyncIds_FullMethodName            = "/HubService/GetAllMessagesBySyncIds"
	HubService_GetSyncMetadataByPrefix_FullMethodName            = "/HubService/GetSyncMetadataByPrefix"
	HubService_GetSyncSnapshotByPrefix_FullMethodName            = "/HubService/GetSyncSnapshotByPrefix"
)

// HubServiceClient is the client API for HubService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HubServiceClient interface {
	// Submit Methods
	SubmitMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
	// Validation Methods
	ValidateMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*ValidationResponse, error)
	// Event Methods
	// @http-api: none
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HubEvent], error)
	// @http-api: events
	GetEvent(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*HubEvent, error)
	// Casts
	// @http-api: castById
	GetCast(ctx context.Context, in *CastId, opts ...grpc.CallOption) (*Message, error)
	GetCastsByFid(ctx context.Context, in *FidRequest, opts ...grpc.CallOption) (*MessagesResponse, error)
	GetCastsByParent(ctx context.Context, in *CastsByParentRequest, opts ...grpc.CallOption) (*MessagesResponse, error)
	GetCastsByMention(ctx context.Context, in *FidRequest, opts ...grpc.CallOption) (*MessagesResponse, error)
	// Reactions
	// @http-api: reactionById
	GetReaction(ctx context.Context, in *ReactionRequest, opts ...grpc.CallOption) (*Message, error)
	GetReactionsByFid(ctx context.Context, in *ReactionsByFidRequest, opts ...grpc.CallOption) (*MessagesResponse, error)
	GetReactionsByCast(ctx context.Context, in *ReactionsByTargetRequest, opts ...grpc.CallOption) (*MessagesResponse, error)
	GetReactionsByTarget(ctx context.Context, in *ReactionsByTargetRequest, opts ...grpc.CallOption) (*MessagesResponse, error)
	// User Data
	// @http-api: none
	GetUserData(ctx context.Context, in *UserDataRequest, opts ...grpc.CallOption) (*Message, error)
	GetUserDataByFid(ctx context.Context, in *FidRequest, opts ...grpc.CallOption) (*MessagesResponse, error)
	// Username Proof
	// @http-api: userNameProofByName
	GetUsernameProof(ctx context.Context, in *UsernameProofRequest, opts ...grpc.CallOption) (*UserNameProof, error)
	GetUserNameProofsByFid(ctx context.Context, in *FidRequest, opts ...grpc.CallOption) (*UsernameProofsResponse, error)
	// Verifications
	// @http-api: none
	GetVerification(ctx context.Context, in *VerificationRequest, opts ...grpc.CallOption) (*Message, error)
	GetVerificationsByFid(ctx context.Context, in *FidRequest, opts ...grpc.CallOption) (*MessagesResponse, error)
	// OnChain Events
	// @http-api: none
	GetOnChainSigner(ctx context.Context, in *SignerRequest, opts ...grpc.CallOption) (*OnChainEvent, error)
	GetOnChainSignersByFid(ctx context.Context, in *FidRequest, opts ...grpc.CallOption) (*OnChainEventResponse, error)
	// @http-api: none
	GetOnChainEvents(ctx context.Context, in *OnChainEventRequest, opts ...grpc.CallOption) (*OnChainEventResponse, error)
	// @http-api: none
	GetIdRegistryOnChainEvent(ctx context.Context, in *FidRequest, opts ...grpc.CallOption) (*OnChainEvent, error)
	// @http-api: onChainIdRegistryEventByAddress
	GetIdRegistryOnChainEventByAddress(ctx context.Context, in *IdRegistryEventByAddressRequest, opts ...grpc.CallOption) (*OnChainEvent, error)
	// @http-api: storageLimitsByFid
	GetCurrentStorageLimitsByFid(ctx context.Context, in *FidRequest, opts ...grpc.CallOption) (*StorageLimitsResponse, error)
	GetFids(ctx context.Context, in *FidsRequest, opts ...grpc.CallOption) (*FidsResponse, error)
	// Links
	// @http-api: linkById
	GetLink(ctx context.Context, in *LinkRequest, opts ...grpc.CallOption) (*Message, error)
	GetLinksByFid(ctx context.Context, in *LinksByFidRequest, opts ...grpc.CallOption) (*MessagesResponse, error)
	// @http-api: linksByTargetFid
	GetLinksByTarget(ctx context.Context, in *LinksByTargetRequest, opts ...grpc.CallOption) (*MessagesResponse, error)
	// Bulk Methods
	// The Bulk methods don't have corresponding HTTP API endpoints because the
	// regular endpoints can be used to get all the messages
	// @http-api: none
	GetAllCastMessagesByFid(ctx context.Context, in *FidRequest, opts ...grpc.CallOption) (*MessagesResponse, error)
	// @http-api: none
	GetAllReactionMessagesByFid(ctx context.Context, in *FidRequest, opts ...grpc.CallOption) (*MessagesResponse, error)
	// @http-api: none
	GetAllVerificationMessagesByFid(ctx context.Context, in *FidRequest, opts ...grpc.CallOption) (*MessagesResponse, error)
	// @http-api: none
	GetAllUserDataMessagesByFid(ctx context.Context, in *FidRequest, opts ...grpc.CallOption) (*MessagesResponse, error)
	// @http-api: none
	GetAllLinkMessagesByFid(ctx context.Context, in *FidRequest, opts ...grpc.CallOption) (*MessagesResponse, error)
	// @http-api: none
	GetLinkCompactStateMessageByFid(ctx context.Context, in *FidRequest, opts ...grpc.CallOption) (*MessagesResponse, error)
	// Sync Methods
	GetInfo(ctx context.Context, in *HubInfoRequest, opts ...grpc.CallOption) (*HubInfoResponse, error)
	GetCurrentPeers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ContactInfoResponse, error)
	// @http-api: none
	StopSync(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SyncStatusResponse, error)
	// This is experimental, do not rely on this endpoint existing in the future
	// @http-api: none
	ForceSync(ctx context.Context, in *SyncStatusRequest, opts ...grpc.CallOption) (*SyncStatusResponse, error)
	// @http-api: none
	GetSyncStatus(ctx context.Context, in *SyncStatusRequest, opts ...grpc.CallOption) (*SyncStatusResponse, error)
	// @http-api: none
	GetAllSyncIdsByPrefix(ctx context.Context, in *TrieNodePrefix, opts ...grpc.CallOption) (*SyncIds, error)
	// @http-api: none
	GetAllMessagesBySyncIds(ctx context.Context, in *SyncIds, opts ...grpc.CallOption) (*MessagesResponse, error)
	// @http-api: none
	GetSyncMetadataByPrefix(ctx context.Context, in *TrieNodePrefix, opts ...grpc.CallOption) (*TrieNodeMetadataResponse, error)
	// @http-api: none
	GetSyncSnapshotByPrefix(ctx context.Context, in *TrieNodePrefix, opts ...grpc.CallOption) (*TrieNodeSnapshotResponse, error)
}

type hubServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHubServiceClient(cc grpc.ClientConnInterface) HubServiceClient {
	return &hubServiceClient{cc}
}

func (c *hubServiceClient) SubmitMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, HubService_SubmitMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) ValidateMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*ValidationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidationResponse)
	err := c.cc.Invoke(ctx, HubService_ValidateMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HubEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HubService_ServiceDesc.Streams[0], HubService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, HubEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HubService_SubscribeClient = grpc.ServerStreamingClient[HubEvent]

func (c *hubServiceClient) GetEvent(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*HubEvent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HubEvent)
	err := c.cc.Invoke(ctx, HubService_GetEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) GetCast(ctx context.Context, in *CastId, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, HubService_GetCast_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) GetCastsByFid(ctx context.Context, in *FidRequest, opts ...grpc.CallOption) (*MessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessagesResponse)
	err := c.cc.Invoke(ctx, HubService_GetCastsByFid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) GetCastsByParent(ctx context.Context, in *CastsByParentRequest, opts ...grpc.CallOption) (*MessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessagesResponse)
	err := c.cc.Invoke(ctx, HubService_GetCastsByParent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) GetCastsByMention(ctx context.Context, in *FidRequest, opts ...grpc.CallOption) (*MessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessagesResponse)
	err := c.cc.Invoke(ctx, HubService_GetCastsByMention_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) GetReaction(ctx context.Context, in *ReactionRequest, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, HubService_GetReaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) GetReactionsByFid(ctx context.Context, in *ReactionsByFidRequest, opts ...grpc.CallOption) (*MessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessagesResponse)
	err := c.cc.Invoke(ctx, HubService_GetReactionsByFid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) GetReactionsByCast(ctx context.Context, in *ReactionsByTargetRequest, opts ...grpc.CallOption) (*MessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessagesResponse)
	err := c.cc.Invoke(ctx, HubService_GetReactionsByCast_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) GetReactionsByTarget(ctx context.Context, in *ReactionsByTargetRequest, opts ...grpc.CallOption) (*MessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessagesResponse)
	err := c.cc.Invoke(ctx, HubService_GetReactionsByTarget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) GetUserData(ctx context.Context, in *UserDataRequest, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, HubService_GetUserData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) GetUserDataByFid(ctx context.Context, in *FidRequest, opts ...grpc.CallOption) (*MessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessagesResponse)
	err := c.cc.Invoke(ctx, HubService_GetUserDataByFid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) GetUsernameProof(ctx context.Context, in *UsernameProofRequest, opts ...grpc.CallOption) (*UserNameProof, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserNameProof)
	err := c.cc.Invoke(ctx, HubService_GetUsernameProof_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) GetUserNameProofsByFid(ctx context.Context, in *FidRequest, opts ...grpc.CallOption) (*UsernameProofsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UsernameProofsResponse)
	err := c.cc.Invoke(ctx, HubService_GetUserNameProofsByFid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) GetVerification(ctx context.Context, in *VerificationRequest, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, HubService_GetVerification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) GetVerificationsByFid(ctx context.Context, in *FidRequest, opts ...grpc.CallOption) (*MessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessagesResponse)
	err := c.cc.Invoke(ctx, HubService_GetVerificationsByFid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) GetOnChainSigner(ctx context.Context, in *SignerRequest, opts ...grpc.CallOption) (*OnChainEvent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OnChainEvent)
	err := c.cc.Invoke(ctx, HubService_GetOnChainSigner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) GetOnChainSignersByFid(ctx context.Context, in *FidRequest, opts ...grpc.CallOption) (*OnChainEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OnChainEventResponse)
	err := c.cc.Invoke(ctx, HubService_GetOnChainSignersByFid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) GetOnChainEvents(ctx context.Context, in *OnChainEventRequest, opts ...grpc.CallOption) (*OnChainEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OnChainEventResponse)
	err := c.cc.Invoke(ctx, HubService_GetOnChainEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) GetIdRegistryOnChainEvent(ctx context.Context, in *FidRequest, opts ...grpc.CallOption) (*OnChainEvent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OnChainEvent)
	err := c.cc.Invoke(ctx, HubService_GetIdRegistryOnChainEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) GetIdRegistryOnChainEventByAddress(ctx context.Context, in *IdRegistryEventByAddressRequest, opts ...grpc.CallOption) (*OnChainEvent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OnChainEvent)
	err := c.cc.Invoke(ctx, HubService_GetIdRegistryOnChainEventByAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) GetCurrentStorageLimitsByFid(ctx context.Context, in *FidRequest, opts ...grpc.CallOption) (*StorageLimitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StorageLimitsResponse)
	err := c.cc.Invoke(ctx, HubService_GetCurrentStorageLimitsByFid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) GetFids(ctx context.Context, in *FidsRequest, opts ...grpc.CallOption) (*FidsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FidsResponse)
	err := c.cc.Invoke(ctx, HubService_GetFids_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) GetLink(ctx context.Context, in *LinkRequest, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, HubService_GetLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) GetLinksByFid(ctx context.Context, in *LinksByFidRequest, opts ...grpc.CallOption) (*MessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessagesResponse)
	err := c.cc.Invoke(ctx, HubService_GetLinksByFid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) GetLinksByTarget(ctx context.Context, in *LinksByTargetRequest, opts ...grpc.CallOption) (*MessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessagesResponse)
	err := c.cc.Invoke(ctx, HubService_GetLinksByTarget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) GetAllCastMessagesByFid(ctx context.Context, in *FidRequest, opts ...grpc.CallOption) (*MessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessagesResponse)
	err := c.cc.Invoke(ctx, HubService_GetAllCastMessagesByFid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) GetAllReactionMessagesByFid(ctx context.Context, in *FidRequest, opts ...grpc.CallOption) (*MessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessagesResponse)
	err := c.cc.Invoke(ctx, HubService_GetAllReactionMessagesByFid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) GetAllVerificationMessagesByFid(ctx context.Context, in *FidRequest, opts ...grpc.CallOption) (*MessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessagesResponse)
	err := c.cc.Invoke(ctx, HubService_GetAllVerificationMessagesByFid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) GetAllUserDataMessagesByFid(ctx context.Context, in *FidRequest, opts ...grpc.CallOption) (*MessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessagesResponse)
	err := c.cc.Invoke(ctx, HubService_GetAllUserDataMessagesByFid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) GetAllLinkMessagesByFid(ctx context.Context, in *FidRequest, opts ...grpc.CallOption) (*MessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessagesResponse)
	err := c.cc.Invoke(ctx, HubService_GetAllLinkMessagesByFid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) GetLinkCompactStateMessageByFid(ctx context.Context, in *FidRequest, opts ...grpc.CallOption) (*MessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessagesResponse)
	err := c.cc.Invoke(ctx, HubService_GetLinkCompactStateMessageByFid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) GetInfo(ctx context.Context, in *HubInfoRequest, opts ...grpc.CallOption) (*HubInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HubInfoResponse)
	err := c.cc.Invoke(ctx, HubService_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) GetCurrentPeers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ContactInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContactInfoResponse)
	err := c.cc.Invoke(ctx, HubService_GetCurrentPeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) StopSync(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SyncStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncStatusResponse)
	err := c.cc.Invoke(ctx, HubService_StopSync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) ForceSync(ctx context.Context, in *SyncStatusRequest, opts ...grpc.CallOption) (*SyncStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncStatusResponse)
	err := c.cc.Invoke(ctx, HubService_ForceSync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) GetSyncStatus(ctx context.Context, in *SyncStatusRequest, opts ...grpc.CallOption) (*SyncStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncStatusResponse)
	err := c.cc.Invoke(ctx, HubService_GetSyncStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) GetAllSyncIdsByPrefix(ctx context.Context, in *TrieNodePrefix, opts ...grpc.CallOption) (*SyncIds, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncIds)
	err := c.cc.Invoke(ctx, HubService_GetAllSyncIdsByPrefix_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) GetAllMessagesBySyncIds(ctx context.Context, in *SyncIds, opts ...grpc.CallOption) (*MessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessagesResponse)
	err := c.cc.Invoke(ctx, HubService_GetAllMessagesBySyncIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) GetSyncMetadataByPrefix(ctx context.Context, in *TrieNodePrefix, opts ...grpc.CallOption) (*TrieNodeMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrieNodeMetadataResponse)
	err := c.cc.Invoke(ctx, HubService_GetSyncMetadataByPrefix_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) GetSyncSnapshotByPrefix(ctx context.Context, in *TrieNodePrefix, opts ...grpc.CallOption) (*TrieNodeSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrieNodeSnapshotResponse)
	err := c.cc.Invoke(ctx, HubService_GetSyncSnapshotByPrefix_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HubServiceServer is the server API for HubService service.
// All implementations must embed UnimplementedHubServiceServer
// for forward compatibility.
type HubServiceServer interface {
	// Submit Methods
	SubmitMessage(context.Context, *Message) (*Message, error)
	// Validation Methods
	ValidateMessage(context.Context, *Message) (*ValidationResponse, error)
	// Event Methods
	// @http-api: none
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[HubEvent]) error
	// @http-api: events
	GetEvent(context.Context, *EventRequest) (*HubEvent, error)
	// Casts
	// @http-api: castById
	GetCast(context.Context, *CastId) (*Message, error)
	GetCastsByFid(context.Context, *FidRequest) (*MessagesResponse, error)
	GetCastsByParent(context.Context, *CastsByParentRequest) (*MessagesResponse, error)
	GetCastsByMention(context.Context, *FidRequest) (*MessagesResponse, error)
	// Reactions
	// @http-api: reactionById
	GetReaction(context.Context, *ReactionRequest) (*Message, error)
	GetReactionsByFid(context.Context, *ReactionsByFidRequest) (*MessagesResponse, error)
	GetReactionsByCast(context.Context, *ReactionsByTargetRequest) (*MessagesResponse, error)
	GetReactionsByTarget(context.Context, *ReactionsByTargetRequest) (*MessagesResponse, error)
	// User Data
	// @http-api: none
	GetUserData(context.Context, *UserDataRequest) (*Message, error)
	GetUserDataByFid(context.Context, *FidRequest) (*MessagesResponse, error)
	// Username Proof
	// @http-api: userNameProofByName
	GetUsernameProof(context.Context, *UsernameProofRequest) (*UserNameProof, error)
	GetUserNameProofsByFid(context.Context, *FidRequest) (*UsernameProofsResponse, error)
	// Verifications
	// @http-api: none
	GetVerification(context.Context, *VerificationRequest) (*Message, error)
	GetVerificationsByFid(context.Context, *FidRequest) (*MessagesResponse, error)
	// OnChain Events
	// @http-api: none
	GetOnChainSigner(context.Context, *SignerRequest) (*OnChainEvent, error)
	GetOnChainSignersByFid(context.Context, *FidRequest) (*OnChainEventResponse, error)
	// @http-api: none
	GetOnChainEvents(context.Context, *OnChainEventRequest) (*OnChainEventResponse, error)
	// @http-api: none
	GetIdRegistryOnChainEvent(context.Context, *FidRequest) (*OnChainEvent, error)
	// @http-api: onChainIdRegistryEventByAddress
	GetIdRegistryOnChainEventByAddress(context.Context, *IdRegistryEventByAddressRequest) (*OnChainEvent, error)
	// @http-api: storageLimitsByFid
	GetCurrentStorageLimitsByFid(context.Context, *FidRequest) (*StorageLimitsResponse, error)
	GetFids(context.Context, *FidsRequest) (*FidsResponse, error)
	// Links
	// @http-api: linkById
	GetLink(context.Context, *LinkRequest) (*Message, error)
	GetLinksByFid(context.Context, *LinksByFidRequest) (*MessagesResponse, error)
	// @http-api: linksByTargetFid
	GetLinksByTarget(context.Context, *LinksByTargetRequest) (*MessagesResponse, error)
	// Bulk Methods
	// The Bulk methods don't have corresponding HTTP API endpoints because the
	// regular endpoints can be used to get all the messages
	// @http-api: none
	GetAllCastMessagesByFid(context.Context, *FidRequest) (*MessagesResponse, error)
	// @http-api: none
	GetAllReactionMessagesByFid(context.Context, *FidRequest) (*MessagesResponse, error)
	// @http-api: none
	GetAllVerificationMessagesByFid(context.Context, *FidRequest) (*MessagesResponse, error)
	// @http-api: none
	GetAllUserDataMessagesByFid(context.Context, *FidRequest) (*MessagesResponse, error)
	// @http-api: none
	GetAllLinkMessagesByFid(context.Context, *FidRequest) (*MessagesResponse, error)
	// @http-api: none
	GetLinkCompactStateMessageByFid(context.Context, *FidRequest) (*MessagesResponse, error)
	// Sync Methods
	GetInfo(context.Context, *HubInfoRequest) (*HubInfoResponse, error)
	GetCurrentPeers(context.Context, *Empty) (*ContactInfoResponse, error)
	// @http-api: none
	StopSync(context.Context, *Empty) (*SyncStatusResponse, error)
	// This is experimental, do not rely on this endpoint existing in the future
	// @http-api: none
	ForceSync(context.Context, *SyncStatusRequest) (*SyncStatusResponse, error)
	// @http-api: none
	GetSyncStatus(context.Context, *SyncStatusRequest) (*SyncStatusResponse, error)
	// @http-api: none
	GetAllSyncIdsByPrefix(context.Context, *TrieNodePrefix) (*SyncIds, error)
	// @http-api: none
	GetAllMessagesBySyncIds(context.Context, *SyncIds) (*MessagesResponse, error)
	// @http-api: none
	GetSyncMetadataByPrefix(context.Context, *TrieNodePrefix) (*TrieNodeMetadataResponse, error)
	// @http-api: none
	GetSyncSnapshotByPrefix(context.Context, *TrieNodePrefix) (*TrieNodeSnapshotResponse, error)
	mustEmbedUnimplementedHubServiceServer()
}

// UnimplementedHubServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHubServiceServer struct{}

func (UnimplementedHubServiceServer) SubmitMessage(context.Context, *Message) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitMessage not implemented")
}
func (UnimplementedHubServiceServer) ValidateMessage(context.Context, *Message) (*ValidationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateMessage not implemented")
}
func (UnimplementedHubServiceServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[HubEvent]) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedHubServiceServer) GetEvent(context.Context, *EventRequest) (*HubEvent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEvent not implemented")
}
func (UnimplementedHubServiceServer) GetCast(context.Context, *CastId) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCast not implemented")
}
func (UnimplementedHubServiceServer) GetCastsByFid(context.Context, *FidRequest) (*MessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCastsByFid not implemented")
}
func (UnimplementedHubServiceServer) GetCastsByParent(context.Context, *CastsByParentRequest) (*MessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCastsByParent not implemented")
}
func (UnimplementedHubServiceServer) GetCastsByMention(context.Context, *FidRequest) (*MessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCastsByMention not implemented")
}
func (UnimplementedHubServiceServer) GetReaction(context.Context, *ReactionRequest) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReaction not implemented")
}
func (UnimplementedHubServiceServer) GetReactionsByFid(context.Context, *ReactionsByFidRequest) (*MessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReactionsByFid not implemented")
}
func (UnimplementedHubServiceServer) GetReactionsByCast(context.Context, *ReactionsByTargetRequest) (*MessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReactionsByCast not implemented")
}
func (UnimplementedHubServiceServer) GetReactionsByTarget(context.Context, *ReactionsByTargetRequest) (*MessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReactionsByTarget not implemented")
}
func (UnimplementedHubServiceServer) GetUserData(context.Context, *UserDataRequest) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserData not implemented")
}
func (UnimplementedHubServiceServer) GetUserDataByFid(context.Context, *FidRequest) (*MessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserDataByFid not implemented")
}
func (UnimplementedHubServiceServer) GetUsernameProof(context.Context, *UsernameProofRequest) (*UserNameProof, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsernameProof not implemented")
}
func (UnimplementedHubServiceServer) GetUserNameProofsByFid(context.Context, *FidRequest) (*UsernameProofsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserNameProofsByFid not implemented")
}
func (UnimplementedHubServiceServer) GetVerification(context.Context, *VerificationRequest) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVerification not implemented")
}
func (UnimplementedHubServiceServer) GetVerificationsByFid(context.Context, *FidRequest) (*MessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVerificationsByFid not implemented")
}
func (UnimplementedHubServiceServer) GetOnChainSigner(context.Context, *SignerRequest) (*OnChainEvent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOnChainSigner not implemented")
}
func (UnimplementedHubServiceServer) GetOnChainSignersByFid(context.Context, *FidRequest) (*OnChainEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOnChainSignersByFid not implemented")
}
func (UnimplementedHubServiceServer) GetOnChainEvents(context.Context, *OnChainEventRequest) (*OnChainEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOnChainEvents not implemented")
}
func (UnimplementedHubServiceServer) GetIdRegistryOnChainEvent(context.Context, *FidRequest) (*OnChainEvent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIdRegistryOnChainEvent not implemented")
}
func (UnimplementedHubServiceServer) GetIdRegistryOnChainEventByAddress(context.Context, *IdRegistryEventByAddressRequest) (*OnChainEvent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIdRegistryOnChainEventByAddress not implemented")
}
func (UnimplementedHubServiceServer) GetCurrentStorageLimitsByFid(context.Context, *FidRequest) (*StorageLimitsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrentStorageLimitsByFid not implemented")
}
func (UnimplementedHubServiceServer) GetFids(context.Context, *FidsRequest) (*FidsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFids not implemented")
}
func (UnimplementedHubServiceServer) GetLink(context.Context, *LinkRequest) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLink not implemented")
}
func (UnimplementedHubServiceServer) GetLinksByFid(context.Context, *LinksByFidRequest) (*MessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLinksByFid not implemented")
}
func (UnimplementedHubServiceServer) GetLinksByTarget(context.Context, *LinksByTargetRequest) (*MessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLinksByTarget not implemented")
}
func (UnimplementedHubServiceServer) GetAllCastMessagesByFid(context.Context, *FidRequest) (*MessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllCastMessagesByFid not implemented")
}
func (UnimplementedHubServiceServer) GetAllReactionMessagesByFid(context.Context, *FidRequest) (*MessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllReactionMessagesByFid not implemented")
}
func (UnimplementedHubServiceServer) GetAllVerificationMessagesByFid(context.Context, *FidRequest) (*MessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllVerificationMessagesByFid not implemented")
}
func (UnimplementedHubServiceServer) GetAllUserDataMessagesByFid(context.Context, *FidRequest) (*MessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllUserDataMessagesByFid not implemented")
}
func (UnimplementedHubServiceServer) GetAllLinkMessagesByFid(context.Context, *FidRequest) (*MessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllLinkMessagesByFid not implemented")
}
func (UnimplementedHubServiceServer) GetLinkCompactStateMessageByFid(context.Context, *FidRequest) (*MessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLinkCompactStateMessageByFid not implemented")
}
func (UnimplementedHubServiceServer) GetInfo(context.Context, *HubInfoRequest) (*HubInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedHubServiceServer) GetCurrentPeers(context.Context, *Empty) (*ContactInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrentPeers not implemented")
}
func (UnimplementedHubServiceServer) StopSync(context.Context, *Empty) (*SyncStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopSync not implemented")
}
func (UnimplementedHubServiceServer) ForceSync(context.Context, *SyncStatusRequest) (*SyncStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForceSync not implemented")
}
func (UnimplementedHubServiceServer) GetSyncStatus(context.Context, *SyncStatusRequest) (*SyncStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSyncStatus not implemented")
}
func (UnimplementedHubServiceServer) GetAllSyncIdsByPrefix(context.Context, *TrieNodePrefix) (*SyncIds, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllSyncIdsByPrefix not implemented")
}
func (UnimplementedHubServiceServer) GetAllMessagesBySyncIds(context.Context, *SyncIds) (*MessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllMessagesBySyncIds not implemented")
}
func (UnimplementedHubServiceServer) GetSyncMetadataByPrefix(context.Context, *TrieNodePrefix) (*TrieNodeMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSyncMetadataByPrefix not implemented")
}
func (UnimplementedHubServiceServer) GetSyncSnapshotByPrefix(context.Context, *TrieNodePrefix) (*TrieNodeSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSyncSnapshotByPrefix not implemented")
}
func (UnimplementedHubServiceServer) mustEmbedUnimplementedHubServiceServer() {}
func (UnimplementedHubServiceServer) testEmbeddedByValue()                    {}

// UnsafeHubServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HubServiceServer will
// result in compilation errors.
type UnsafeHubServiceServer interface {
	mustEmbedUnimplementedHubServiceServer()
}

func RegisterHubServiceServer(s grpc.ServiceRegistrar, srv HubServiceServer) {
	// If the following call pancis, it indicates UnimplementedHubServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HubService_ServiceDesc, srv)
}

func _HubService_SubmitMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).SubmitMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_SubmitMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).SubmitMessage(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_ValidateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).ValidateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_ValidateMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).ValidateMessage(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HubServiceServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, HubEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HubService_SubscribeServer = grpc.ServerStreamingServer[HubEvent]

func _HubService_GetEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetEvent(ctx, req.(*EventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_GetCast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CastId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetCast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetCast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetCast(ctx, req.(*CastId))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_GetCastsByFid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetCastsByFid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetCastsByFid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetCastsByFid(ctx, req.(*FidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_GetCastsByParent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CastsByParentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetCastsByParent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetCastsByParent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetCastsByParent(ctx, req.(*CastsByParentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_GetCastsByMention_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetCastsByMention(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetCastsByMention_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetCastsByMention(ctx, req.(*FidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_GetReaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetReaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetReaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetReaction(ctx, req.(*ReactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_GetReactionsByFid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReactionsByFidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetReactionsByFid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetReactionsByFid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetReactionsByFid(ctx, req.(*ReactionsByFidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_GetReactionsByCast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReactionsByTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetReactionsByCast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetReactionsByCast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetReactionsByCast(ctx, req.(*ReactionsByTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_GetReactionsByTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReactionsByTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetReactionsByTarget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetReactionsByTarget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetReactionsByTarget(ctx, req.(*ReactionsByTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_GetUserData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetUserData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetUserData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetUserData(ctx, req.(*UserDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_GetUserDataByFid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetUserDataByFid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetUserDataByFid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetUserDataByFid(ctx, req.(*FidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_GetUsernameProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsernameProofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetUsernameProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetUsernameProof_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetUsernameProof(ctx, req.(*UsernameProofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_GetUserNameProofsByFid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetUserNameProofsByFid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetUserNameProofsByFid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetUserNameProofsByFid(ctx, req.(*FidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_GetVerification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetVerification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetVerification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetVerification(ctx, req.(*VerificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_GetVerificationsByFid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetVerificationsByFid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetVerificationsByFid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetVerificationsByFid(ctx, req.(*FidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_GetOnChainSigner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetOnChainSigner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetOnChainSigner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetOnChainSigner(ctx, req.(*SignerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_GetOnChainSignersByFid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetOnChainSignersByFid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetOnChainSignersByFid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetOnChainSignersByFid(ctx, req.(*FidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_GetOnChainEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnChainEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetOnChainEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetOnChainEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetOnChainEvents(ctx, req.(*OnChainEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_GetIdRegistryOnChainEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetIdRegistryOnChainEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetIdRegistryOnChainEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetIdRegistryOnChainEvent(ctx, req.(*FidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_GetIdRegistryOnChainEventByAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRegistryEventByAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetIdRegistryOnChainEventByAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetIdRegistryOnChainEventByAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetIdRegistryOnChainEventByAddress(ctx, req.(*IdRegistryEventByAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_GetCurrentStorageLimitsByFid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetCurrentStorageLimitsByFid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetCurrentStorageLimitsByFid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetCurrentStorageLimitsByFid(ctx, req.(*FidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_GetFids_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FidsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetFids(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetFids_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetFids(ctx, req.(*FidsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_GetLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetLink(ctx, req.(*LinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_GetLinksByFid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinksByFidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetLinksByFid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetLinksByFid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetLinksByFid(ctx, req.(*LinksByFidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_GetLinksByTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinksByTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetLinksByTarget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetLinksByTarget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetLinksByTarget(ctx, req.(*LinksByTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_GetAllCastMessagesByFid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetAllCastMessagesByFid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetAllCastMessagesByFid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetAllCastMessagesByFid(ctx, req.(*FidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_GetAllReactionMessagesByFid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetAllReactionMessagesByFid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetAllReactionMessagesByFid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetAllReactionMessagesByFid(ctx, req.(*FidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_GetAllVerificationMessagesByFid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetAllVerificationMessagesByFid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetAllVerificationMessagesByFid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetAllVerificationMessagesByFid(ctx, req.(*FidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_GetAllUserDataMessagesByFid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetAllUserDataMessagesByFid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetAllUserDataMessagesByFid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetAllUserDataMessagesByFid(ctx, req.(*FidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_GetAllLinkMessagesByFid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetAllLinkMessagesByFid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetAllLinkMessagesByFid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetAllLinkMessagesByFid(ctx, req.(*FidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_GetLinkCompactStateMessageByFid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetLinkCompactStateMessageByFid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetLinkCompactStateMessageByFid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetLinkCompactStateMessageByFid(ctx, req.(*FidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HubInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetInfo(ctx, req.(*HubInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_GetCurrentPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetCurrentPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetCurrentPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetCurrentPeers(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_StopSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).StopSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_StopSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).StopSync(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_ForceSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).ForceSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_ForceSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).ForceSync(ctx, req.(*SyncStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_GetSyncStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetSyncStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetSyncStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetSyncStatus(ctx, req.(*SyncStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_GetAllSyncIdsByPrefix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrieNodePrefix)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetAllSyncIdsByPrefix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetAllSyncIdsByPrefix_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetAllSyncIdsByPrefix(ctx, req.(*TrieNodePrefix))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_GetAllMessagesBySyncIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncIds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetAllMessagesBySyncIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetAllMessagesBySyncIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetAllMessagesBySyncIds(ctx, req.(*SyncIds))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_GetSyncMetadataByPrefix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrieNodePrefix)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetSyncMetadataByPrefix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetSyncMetadataByPrefix_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetSyncMetadataByPrefix(ctx, req.(*TrieNodePrefix))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_GetSyncSnapshotByPrefix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrieNodePrefix)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetSyncSnapshotByPrefix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetSyncSnapshotByPrefix_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetSyncSnapshotByPrefix(ctx, req.(*TrieNodePrefix))
	}
	return interceptor(ctx, in, info, handler)
}

// HubService_ServiceDesc is the grpc.ServiceDesc for HubService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HubService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "HubService",
	HandlerType: (*HubServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitMessage",
			Handler:    _HubService_SubmitMessage_Handler,
		},
		{
			MethodName: "ValidateMessage",
			Handler:    _HubService_ValidateMessage_Handler,
		},
		{
			MethodName: "GetEvent",
			Handler:    _HubService_GetEvent_Handler,
		},
		{
			MethodName: "GetCast",
			Handler:    _HubService_GetCast_Handler,
		},
		{
			MethodName: "GetCastsByFid",
			Handler:    _HubService_GetCastsByFid_Handler,
		},
		{
			MethodName: "GetCastsByParent",
			Handler:    _HubService_GetCastsByParent_Handler,
		},
		{
			MethodName: "GetCastsByMention",
			Handler:    _HubService_GetCastsByMention_Handler,
		},
		{
			MethodName: "GetReaction",
			Handler:    _HubService_GetReaction_Handler,
		},
		{
			MethodName: "GetReactionsByFid",
			Handler:    _HubService_GetReactionsByFid_Handler,
		},
		{
			MethodName: "GetReactionsByCast",
			Handler:    _HubService_GetReactionsByCast_Handler,
		},
		{
			MethodName: "GetReactionsByTarget",
			Handler:    _HubService_GetReactionsByTarget_Handler,
		},
		{
			MethodName: "GetUserData",
			Handler:    _HubService_GetUserData_Handler,
		},
		{
			MethodName: "GetUserDataByFid",
			Handler:    _HubService_GetUserDataByFid_Handler,
		},
		{
			MethodName: "GetUsernameProof",
			Handler:    _HubService_GetUsernameProof_Handler,
		},
		{
			MethodName: "GetUserNameProofsByFid",
			Handler:    _HubService_GetUserNameProofsByFid_Handler,
		},
		{
			MethodName: "GetVerification",
			Handler:    _HubService_GetVerification_Handler,
		},
		{
			MethodName: "GetVerificationsByFid",
			Handler:    _HubService_GetVerificationsByFid_Handler,
		},
		{
			MethodName: "GetOnChainSigner",
			Handler:    _HubService_GetOnChainSigner_Handler,
		},
		{
			MethodName: "GetOnChainSignersByFid",
			Handler:    _HubService_GetOnChainSignersByFid_Handler,
		},
		{
			MethodName: "GetOnChainEvents",
			Handler:    _HubService_GetOnChainEvents_Handler,
		},
		{
			MethodName: "GetIdRegistryOnChainEvent",
			Handler:    _HubService_GetIdRegistryOnChainEvent_Handler,
		},
		{
			MethodName: "GetIdRegistryOnChainEventByAddress",
			Handler:    _HubService_GetIdRegistryOnChainEventByAddress_Handler,
		},
		{
			MethodName: "GetCurrentStorageLimitsByFid",
			Handler:    _HubService_GetCurrentStorageLimitsByFid_Handler,
		},
		{
			MethodName: "GetFids",
			Handler:    _HubService_GetFids_Handler,
		},
		{
			MethodName: "GetLink",
			Handler:    _HubService_GetLink_Handler,
		},
		{
			MethodName: "GetLinksByFid",
			Handler:    _HubService_GetLinksByFid_Handler,
		},
		{
			MethodName: "GetLinksByTarget",
			Handler:    _HubService_GetLinksByTarget_Handler,
		},
		{
			MethodName: "GetAllCastMessagesByFid",
			Handler:    _HubService_GetAllCastMessagesByFid_Handler,
		},
		{
			MethodName: "GetAllReactionMessagesByFid",
			Handler:    _HubService_GetAllReactionMessagesByFid_Handler,
		},
		{
			MethodName: "GetAllVerificationMessagesByFid",
			Handler:    _HubService_GetAllVerificationMessagesByFid_Handler,
		},
		{
			MethodName: "GetAllUserDataMessagesByFid",
			Handler:    _HubService_GetAllUserDataMessagesByFid_Handler,
		},
		{
			MethodName: "GetAllLinkMessagesByFid",
			Handler:    _HubService_GetAllLinkMessagesByFid_Handler,
		},
		{
			MethodName: "GetLinkCompactStateMessageByFid",
			Handler:    _HubService_GetLinkCompactStateMessageByFid_Handler,
		},
		{
			MethodName: "GetInfo",
			Handler:    _HubService_GetInfo_Handler,
		},
		{
			MethodName: "GetCurrentPeers",
			Handler:    _HubService_GetCurrentPeers_Handler,
		},
		{
			MethodName: "StopSync",
			Handler:    _HubService_StopSync_Handler,
		},
		{
			MethodName: "ForceSync",
			Handler:    _HubService_ForceSync_Handler,
		},
		{
			MethodName: "GetSyncStatus",
			Handler:    _HubService_GetSyncStatus_Handler,
		},
		{
			MethodName: "GetAllSyncIdsByPrefix",
			Handler:    _HubService_GetAllSyncIdsByPrefix_Handler,
		},
		{
			MethodName: "GetAllMessagesBySyncIds",
			Handler:    _HubService_GetAllMessagesBySyncIds_Handler,
		},
		{
			MethodName: "GetSyncMetadataByPrefix",
			Handler:    _HubService_GetSyncMetadataByPrefix_Handler,
		},
		{
			MethodName: "GetSyncSnapshotByPrefix",
			Handler:    _HubService_GetSyncSnapshotByPrefix_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _HubService_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rpc.proto",
}

const (
	AdminService_RebuildSyncTrie_FullMethodName         = "/AdminService/RebuildSyncTrie"
	AdminService_DeleteAllMessagesFromDb_FullMethodName = "/AdminService/DeleteAllMessagesFromDb"
	AdminService_SubmitOnChainEvent_FullMethodName      = "/AdminService/SubmitOnChainEvent"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminServiceClient interface {
	RebuildSyncTrie(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	DeleteAllMessagesFromDb(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	SubmitOnChainEvent(ctx context.Context, in *OnChainEvent, opts ...grpc.CallOption) (*OnChainEvent, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) RebuildSyncTrie(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AdminService_RebuildSyncTrie_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) DeleteAllMessagesFromDb(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AdminService_DeleteAllMessagesFromDb_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) SubmitOnChainEvent(ctx context.Context, in *OnChainEvent, opts ...grpc.CallOption) (*OnChainEvent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OnChainEvent)
	err := c.cc.Invoke(ctx, AdminService_SubmitOnChainEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility.
type AdminServiceServer interface {
	RebuildSyncTrie(context.Context, *Empty) (*Empty, error)
	DeleteAllMessagesFromDb(context.Context, *Empty) (*Empty, error)
	SubmitOnChainEvent(context.Context, *OnChainEvent) (*OnChainEvent, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) RebuildSyncTrie(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RebuildSyncTrie not implemented")
}
func (UnimplementedAdminServiceServer) DeleteAllMessagesFromDb(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAllMessagesFromDb not implemented")
}
func (UnimplementedAdminServiceServer) SubmitOnChainEvent(context.Context, *OnChainEvent) (*OnChainEvent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitOnChainEvent not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}
func (UnimplementedAdminServiceServer) testEmbeddedByValue()                      {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	// If the following call pancis, it indicates UnimplementedAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_RebuildSyncTrie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).RebuildSyncTrie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_RebuildSyncTrie_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).RebuildSyncTrie(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_DeleteAllMessagesFromDb_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).DeleteAllMessagesFromDb(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_DeleteAllMessagesFromDb_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).DeleteAllMessagesFromDb(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_SubmitOnChainEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnChainEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).SubmitOnChainEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_SubmitOnChainEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).SubmitOnChainEvent(ctx, req.(*OnChainEvent))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RebuildSyncTrie",
			Handler:    _AdminService_RebuildSyncTrie_Handler,
		},
		{
			MethodName: "DeleteAllMessagesFromDb",
			Handler:    _AdminService_DeleteAllMessagesFromDb_Handler,
		},
		{
			MethodName: "SubmitOnChainEvent",
			Handler:    _AdminService_SubmitOnChainEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}
